/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AuthLayout: typeof import('../src/components/bussiness/AuthLayout/index').default
  const CodeBlockModal: typeof import('../src/components/common/Editor/src/TiptapEditor/modals').CodeBlockModal
  const CodeEditor: typeof import('../src/components/common/Editor/src/CodeEditor').default
  const CustomCodeBlockLowlight: typeof import('../src/components/common/Editor/src/TiptapEditor/index').CustomCodeBlockLowlight
  const CustomIframe: typeof import('../src/components/common/Editor/src/TiptapEditor/nodes').CustomIframe
  const CustomVideo: typeof import('../src/components/common/Editor/src/TiptapEditor/nodes').CustomVideo
  const Editor: typeof import('../src/components/common/Editor/src/Editor').default
  const EditorType: typeof import('../src/components/common/Editor/types').EditorType
  const Fragment: typeof import('react').Fragment
  const IframeModal: typeof import('../src/components/common/Editor/src/TiptapEditor/modals').IframeModal
  const JsonEditor: typeof import('../src/components/common/Editor/src/JsonEditor').default
  const Link: typeof import('react-router-dom').Link
  const LinkModal: typeof import('../src/components/common/Editor/src/TiptapEditor/index').LinkModal
  const Loading: typeof import('../src/components/common/Loading/index').default
  const MarkdownEditor: typeof import('../src/components/common/Editor/src/MarkdownEditor').default
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const PageContainer: typeof import('../src/components/common/PageContainer/index').default
  const PlainTextEditor: typeof import('../src/components/common/Editor/src/PlainTextEditor').default
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const SloganIcon: typeof import('../src/components/bussiness/AuthLayout/icons/SloganIcon').default
  const StatusBar: typeof import('../src/components/common/Editor/src/TiptapEditor/index').StatusBar
  const Suspense: typeof import('react').Suspense
  const ThemeLoading: typeof import('../src/components/common/Loading/index').ThemeLoading
  const TiptapEditor: typeof import('../src/components/common/Editor/src/TiptapEditor').default
  const Toolbar: typeof import('../src/components/common/Editor/src/TiptapEditor/index').Toolbar
  const VideoModal: typeof import('../src/components/common/Editor/src/TiptapEditor/modals').VideoModal
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const connectSSEServer: typeof import('../src/hooks/useTokenRefresh').connectSSEServer
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const disconnectSSEServer: typeof import('../src/hooks/useTokenRefresh').disconnectSSEServer
  const fetchAllDictEntries: typeof import('../src/hooks/useDictCache').fetchAllDictEntries
  const forwardRef: typeof import('react').forwardRef
  const getDictEntriesByTypeCode: typeof import('../src/hooks/useDictCache').getDictEntriesByTypeCode
  const getDictEntriesOptionsByTypeCode: typeof import('../src/hooks/useDictCache').getDictEntriesOptionsByTypeCode
  const getDictEntryLabel: typeof import('../src/hooks/useDictCache').getDictEntryLabel
  const getDictEntryLabelByValue: typeof import('../src/hooks/useDictCache').getDictEntryLabelByValue
  const getDictTypes: typeof import('../src/hooks/useDictCache').getDictTypes
  const initMonacoWorkers: typeof import('../src/components/common/Editor/src/monaco-loader').initMonacoWorkers
  const isDarkMode: typeof import('../src/components/common/Editor/src/utils').isDarkMode
  const languages: typeof import('../src/components/common/Editor/src/TiptapEditor/index').languages
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const monacoLoader: typeof import('../src/components/common/Editor/src/monaco-loader').default
  const reconnectSSEServer: typeof import('../src/hooks/useTokenRefresh').reconnectSSEServer
  const resetDictCache: typeof import('../src/hooks/useDictCache').resetDictCache
  const startRefreshTimer: typeof import('../src/hooks/useTokenRefresh').startRefreshTimer
  const startTransition: typeof import('react').startTransition
  const stopRefreshTimer: typeof import('../src/hooks/useTokenRefresh').stopRefreshTimer
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAuth: typeof import('../src/hooks/useAuth').useAuth
  const useAuthStore: typeof import('../src/stores/auth').useAuthStore
  const useAutoTableHeight: typeof import('../src/hooks/useTableScrollHeight').useAutoTableHeight
  const useCallback: typeof import('react').useCallback
  const useClipboard: typeof import('../src/hooks/useClipboard').useClipboard
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEcharts: typeof import('../src/hooks/useEcharts').useEcharts
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useKeyStroke: typeof import('../src/hooks/useKeyStroke').useKeyStroke
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const usePageRefreshStore: typeof import('../src/stores/pageRefresh').usePageRefreshStore
  const useParams: typeof import('react-router-dom').useParams
  const useProTableScrollY: typeof import('../src/hooks/useProTableScrollY').useProTableScrollY
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTableScrollHeight: typeof import('../src/hooks/useTableScrollHeight').useTableScrollHeight
  const useTabsStore: typeof import('../src/stores/tabs').useTabsStore
  const useTimes: typeof import('../src/hooks/useTime').useTimes
  const useTiptapEditor: typeof import('../src/components/common/Editor/src/TiptapEditor/useTiptapEditor').useTiptapEditor
  const useTitle: typeof import('../src/hooks/useTitle').useTitle
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
  const useUserStore: typeof import('../src/stores/user').useUserStore
  const useWatermark: typeof import('../src/hooks/useWatermark').useWatermark
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC, ECOption, AuthLayoutProps, EditorProps, CodeEditorProps, JsonEditorProps, MarkdownEditorProps, PlainTextEditorProps, TiptapEditorProps, CodeBlockModalProps, VideoModalProps, IframeModalProps, ThemeLoadingProps, TokenPayload, AuthState, UserState, TabItem } from './autoImports.d'
  import('./autoImports.d')
}
